class MSProj_OrangeBarrageSmall_Slow extends MSProj_GreenBarrageSmall_Slow;

DefaultProperties
{
	ProjFlightTemplate=ParticleSystem'Bounty.Particles.MSProj_BossPhase3_Orange'
	ProjExplosionTemplate=ParticleSystem'Bounty.Particles.MSProj_BossPhase3_Orange_Impact'
}
